sections:
- title: Major changes
  labels:
    - "release/super-feature"
- title: Complete changelog
  labels:
    - "bug"
    - "enhancement"
    - "dependencies"
template: |
  Plugin maven dependency:
  ```xml
  <plugin>
      <groupId>org.tkit.maven</groupId>
      <artifactId>tkit-mp-restclient-plugin</artifactId>
      <version>{{ .Version }}</version>
  </plugin>
  ```
  {{ range $section := .Sections }}{{ if $section.Items }}### {{ $section.GetTitle }}{{ range $item := $section.Items }}
  * [#{{ $item.GetID }}]({{ $item.GetURL }}) - {{ $item.GetTitle }}{{ end }}{{ end }}
  {{ end }}
